hostname: pns-s2

remote_hosts:
  - http://pns-m2.networld.to/index.html
  - http://pns-m2.networld.to/index.php
  - http://pns-m2.networld.to/blog/
  - http://pns-s1.networld.to/index.html
  - http://pns-s1.networld.to/index.php
  - http://pns-s1.networld.to/blog/
  - http://pns-m1.networld.to/index.html
  - http://pns-m1.networld.to/index.php
  - http://pns-m1.networld.to/blog/

rates:
  - 1
  - 20
  - 60
  - 100
  - 200

seconds:
  - 10
  - 10
  - 10
  - 10
  - 10

